name: "Run Server"

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Dependencies
      run: |
        sudo apt update
        sudo apt install gcc nasm -y

    - name: Make
      run: |
        make

    - name: Chmod
      run: chmod +x http_server 

    - name: Run serv
      run: ./http_server
