name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y nasm

    - name: Build the Project
      run: |
        make
        mkdir -p Releases
        mv HTTP Releases/HTTP-$(git rev-parse --short HEAD)

    - name: Upload to GitHub Artifact
      uses: actions/upload-artifact@v3
      with:
        name: HTTP
        path: Releases/
